/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "stm32f407xx.h"


// Function prototype for SysTick handler
void SysTick_Handler(void);


int main(void) {
	// Enable the clock for GPIO Port D
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIODEN;  // Enable GPIO Port D clock

	// Configure PD13 as Output
	GPIOD->MODER &= ~(0x3 << (13 * 2));      // Clear mode bits for PD13
	GPIOD->MODER |= (0x1 << (13 * 2));       // Set PD13 to Output mode

	// Set up SysTick timer
	SysTick->LOAD = 16000000 - 1; // Load the timer for 1 second at 16 MHz clock
	SysTick->VAL = 0;              // Clear the current value register
    SysTick->CTRL = 0x07;         // Enable SysTick, use processor clock, enable interrupt

    // Enable NVIC for SysTick interrupt
    NVIC_SetPriority(SysTick_IRQn, 1); // Set the priority (optional)
    NVIC_EnableIRQ(SysTick_IRQn);       // Enable the SysTick interrupt in the NVIC


//	__asm__ (
//			"MOV R2, #10\n"      // Load 10 into R2
//			"MOV R3, #7\n"// Load 7 into R3
//			"ADD R4, R2, R3\n"// Add R2 and R3, store result in R4
//	);

	while (1) {

	}
}

// SysTick interrupt handler
void SysTick_Handler(void) {
	// Inline assembly to toggle PD13 (LED)
	__asm__ (
			"LDR R0, =0x40020C14\n"  // Load address of GPIOD ODR
			"LDR R1, [R0]\n"// Load the current ODR value into R1
			"EOR R1, R1, #0x2000\n"// Toggle bit 13 (PD13) in R1
			"STR R1, [R0]\n"// Store the new value back to ODR
	);
}

