/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include<stm32f407xx.h>
#include<stdio.h>

//#define FULL
//#define PROGRAM_COUNTER
//#define LINK_REGISTER_1
//#define LINK_REGISTER_2
#define LED

#if defined (FULL)
// Function to perform simple arithmetic
void nested_function(int x) {
	uint32_t y = x * 2;  // Local variable 'y' stored on the stack
    y += 5;         // Perform some operations on  'y'
}

// Function that calls another function
void simple_function(void) {
    uint32_t a = 10;           // Local variable 'a' stored on the stack
    nested_function(a);    // Call to nested_function
}

int main(void) {
	uint32_t a = 10;
    simple_function();    // Call simple_function
    while (1) {}          // Infinite loop to keep the program running
}

#elif defined (PROGRAM_COUNTER)

int main(void) {
	uint32_t num = 0;
    num += 1;    // Call simple_function
    num += 1;
    num += 1;
    while(1){

    }
        return 0;// Infinite loop to keep the program running
}

#elif defined (LINK_REGISTER_1)

void fun1(void);
int main(void)
{
	fun1();
	int num1 = 5;
}

void fun1(void)
{
	int num2 = 20;
}

#elif defined (LINK_REGISTER_2)

void fun1(void);
void fun2(void);

int main(void)  //080001c8:   push    {r7, lr}
{

	fun1();
	int num1 = 5; //080001d2:   movs    r3, #5

}

void fun1(void)      //080001e0:   push    {r7, lr}
{

	int num2 = 20;
	fun2();

}//080001ee:   nop

void fun2(void)      //080001f6:   push    {r7}
{

	int num3 = 25;

}
#elif defined (LED)

int main(void)  //080001c8:   push    {r7, lr}
{
	int num1 = 5; //080001d2:   movs    r3, #5
	num1 = 0;
}

#endif
